[package]
name = "rbx_xml"
description = "Implementation of Roblox's XML file formats, rbxlx and rbxmx"
version = "2.0.1"
license = "MIT"
documentation = "https://docs.rs/rbx_xml"
homepage = "https://github.com/rojo-rbx/rbx-dom"
repository = "https://github.com/rojo-rbx/rbx-dom.git"
readme = "README.md"
authors = [
    "Lucien Greathouse <me@lpghatguy.com>",
    "Micah Reid <git@dekkonot.com>",
    "Ken Loeffler <kenloef@gmail.com>",
]
edition = "2018"

[dependencies]
rbx_dom_weak = { version = "4.1.0", path = "../rbx_dom_weak" }
rbx_reflection = { version = "6.1.0", path = "../rbx_reflection" }
rbx_reflection_database = { version = "2.0.2", path = "../rbx_reflection_database" }

ahash = "0.8.12"
base64 = "0.22"
log = "0.4.29"
xml-rs = "0.8.28"

[dev-dependencies]
env_logger = "0.11"
insta = { version = "1.46.1", features = ["yaml"] }
heck = "0.5"
rbx_reflection_database = { path = "../rbx_reflection_database", features = [
    "debug_always_use_bundled",
] }
